/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package object.notification.java;
import object.notification.java.ObjectA;
import object.notification.java.ObjectB;

public class App {
    public static void main(String[] args) {
        ObjectB objB = new ObjectB();
        ObjectA objA = new ObjectA(objB);
        objA.setValue(70);
    }
}

